# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koma < Formula
  desc "The ultimate CLI manga downloader!"
  homepage "https://github.com/JaneWoo0068/koma"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.1.1/koma_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "afb26d001ba23b87b69f95290d981ae11e4bc05261e19ebfe8f980e6e497cbc7"

      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.1.1/koma_1.1.1_Darwin_arm64.tar.gz"
      sha256 "41c71aa9da92eed1143426940379e7d1db506dcafb111ca2c77445ddbad65920"

      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.1.1/koma_1.1.1_Linux_x86_64.tar.gz"
      sha256 "a9588dae63fba90f300f14ae1bb0a32fefdcac3daf46fbe357985f7aad877996"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.1.1/koma_1.1.1_Linux_arm.tar.gz"
      sha256 "5936b00534f3ca816ab8163967256a687f1cebc721e9bcbd95acab13f2efd737"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.1.1/koma_1.1.1_Linux_arm64.tar.gz"
      sha256 "140f76bb19efb7136eb0d3fc2e1502929d366b29d6986f3ac7861157a1e950fa"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
  end

  test do
    system "#{bin}/koma -v"
  end
end
