# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koma < Formula
  desc "The ultimate CLI manga downloader!"
  homepage "https://github.com/JaneWoo0068/koma"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.0.1/koma_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "4668c988646530828aeb4fb99f2641f3d022d2b38143fb1321e0b1cdb86685a8"

      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.0.1/koma_1.0.1_Darwin_arm64.tar.gz"
      sha256 "d1f946bf68d6ad6a59305bfda7904a97d9c870fc9d06269767e82b49890db15d"

      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.0.1/koma_1.0.1_Linux_x86_64.tar.gz"
      sha256 "e54f1a5e4d506245212525d36b24602503605d439a4c983dd0a2b04b1ff8e54f"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.0.1/koma_1.0.1_Linux_arm.tar.gz"
      sha256 "c85ad8a12ba6515985afc6b204076c2c48050996b3437a13f1870b6f99347137"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JaneWoo0068/koma/releases/download/v1.0.1/koma_1.0.1_Linux_arm64.tar.gz"
      sha256 "a9224e5ac65faaa11b987ee635b361a9fe62c5a914f249129ea97755ea2affe0"
      define_method(:install) do
        bin.install "koma"
        bash_completion.install "completions/koma.bash" => "koma"
        zsh_completion.install "completions/koma.zsh" => "_koma"
        fish_completion.install "completions/koma.fish"
      end
    end
  end

  test do
    system "#{bin}/koma -v"
  end
end
